name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      env:
        CR_PAT: ${{ secrets.CR_PAT }}
      # run: docker build . --file Dockerfile --tag ghcr.io/heyymrdj/docker-k8s-quake3:latest 
      run: echo "$CR_PAT" | docker login ghcr.io -u USERNAME --password-stdin
